# .github/workflows/build-on-push.yml
name: Build and Test on Push

on:
  push:
    branches:
      - main      # Trigger when code is pushed to main branch
    #   - feature/* # Trigger when code is pushed to any branch starting with "feature/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Run tests
        run: npm test