name: Build and Test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: echo "Building the application..."
        
      - name: Run Tests
        run: echo "Running tests..."