name: Deploy

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    # Only run if the triggering workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Production
        run: echo "Deploying to production server..."