name: PR Info Check
on: [pull_request]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Show PR Info
        run: |
          echo "PR Number: ${{ github.event.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"