name: Simple Conditionals Demo
on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  demonstrate:
    runs-on: ubuntu-latest
    steps:
      # Basic echo
      - name: Hello World
        run: echo "Hello from GitHub Actions!"
      
      # Simple if condition (branch check)
      - name: Main Branch Check
        if: github.ref == 'refs/heads/main'
        run: echo "This is running on the MAIN branch"
      
      - name: Dev Branch Check
        if: github.ref == 'refs/heads/dev'
        run: echo "This is running on the DEV branch"
      
      # Event type condition
      - name: On Push Event
        if: github.event_name == 'push'
        run: echo "Triggered by a push event"
      
      - name: On PR Event
        if: github.event_name == 'pull_request'
        run: echo "Triggered by a pull request"
      
      - name: On Workflow Dispatch Event
        if: github.event_name == 'workflow_dispatch'
        run: echo "Triggered by the workflow_dispatch event"
      
      # String functions
      - name: String Checks
        run: |
          echo "Contains 'Actions'? ${{ contains('Hello from GitHub Actions!', 'Actions') }}"
          echo "Starts with 'Hello'? ${{ startsWith('Hello from GitHub Actions!', 'Hello') }}"
          echo "Uppercase: $(echo 'Hello from GitHub Actions!' | tr '[:lower:]' '[:upper:]')"
      
      # Combining conditions
      - name: Combined Condition
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "This is a push to the main branch!"
      
      # Formatting example
      - name: Formatted Message
        run: echo "${{ format('Run {0} triggered by {1}', github.run_number, github.event_name) }}"
      
      # File operations
      - name: Create Test File
        run: echo "test content" > test.txt
    
      # JSON handling
      - name: JSON Example
        run: |
          echo "Original string: ${{ toJSON('Hello World') }}"
          echo "From JSON: ${{ fromJSON('"Hello World"') }}"
      
      # Ternary operator
      - name: Ternary Example
        run: echo "${{ github.ref == 'refs/heads/main' && 'Production' || 'Non-production' }} environment"