name: Dynamic Docker Tagging

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate dynamic Docker tag
        run: |
          COMMIT_HASH=${GITHUB_SHA::7}
          DATE_TAG=$(date +'%Y%m%d-%H%M')
          TAG="myapp-${COMMIT_HASH}-${DATE_TAG}"
          echo "DOCKER_TAG=$TAG" >> $GITHUB_ENV
          echo "Docker tag generated: $TAG"

      - name: Build and tag Docker image
        run: |
          echo "Building Docker image with tag: $DOCKER_TAG"
        # run: |
        #   docker build -t myorg/myapp:$DOCKER_TAG .

    #   - name: Push to DockerHub
    #     run: |
    #       docker push myorg/myapp:$DOCKER_TAG