name: Caller Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  call-reusable:
    uses: ./.github/workflows/25.1. resuable-outputs.yaml
  
  use-outputs:
    needs: call-reusable
    runs-on: ubuntu-latest
    steps:
      - name: Display outputs
        run: |
          echo "Build result: ${{ needs.call-reusable.outputs.build-result }}"
          echo "Test coverage: ${{ needs.call-reusable.outputs.test-coverage }}