name: 26. Build and Deploy
on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: |
        mkdir -p build/
        echo "Built at $(date)" > build/output.txt
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build/
    
    - name: view build output
      run: |
        ls -l build/
        cat build/output.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: view build directory in deploy
      continue-on-error: true  # Continue even if the build directory doesn't exist
      run: |
        ls -l build/

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: build/  # Specify the same path used when uploading
        
    - name: Show artifact contents
      run: |
        ls -lrt
        ls -l build/
        cat build/output.txt