name: Checkout Example

on: [workflow_dispatch]

jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name: List Files Before
        run: ls -lahrt
      
      - name: ✅ Checkout Code
        uses: actions/checkout@v4

      - name: 📂 List Files in Repo After
        run: |
          ls -lahrt
          pwd
