name: First Workflow
on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run shell command
        run: echo "Hello, World!"
      
      - name: List files in current directory
        run: ls -la