name: Dependent Jobs Example
on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the application
        run: echo "Building the app..."
      - name: Wait for 30 seconds
        run: sleep 30s  # Linux/macOS (use 'Start-Sleep -Seconds 30' for Windows)

  test:
    runs-on: ubuntu-latest
    needs: build  # Waits for 'build' to finish
    steps:
      - name: Run tests
        run: echo "Running tests..."
      - name: Wait for 30 seconds
        run: sleep 30s  # Linux/macOS (use 'Start-Sleep -Seconds 30' for Windows)


  deploy:
    runs-on: ubuntu-latest   # Parallel job
    steps:
      - name: Deploy to production
        run: echo "Deploying to production..."
      - name: Wait for 30 seconds
        run: sleep 30s  # Linux/macOS (use 'Start-Sleep -Seconds 30' for Windows)
